version: "3.1"

services:
  hbase:
    image: aaionap/hbase
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 60010:60010

volumes:
  hbase_data:
  hbase_zookeeper_data:

