
version: '3.1'
services:
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka 
      KAFKA_ADVERTISED_PORT: 9092
  
