apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-1
  template:
    metadata:
      labels:
        component: kafka-1
    spec:
      containers:
      - name: kafka-1 
        image: pharosproduction/kafka_k8s:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 9092
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-ip-service:2181
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: $(MY_POD_IP)
        tty: true
        livenessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        # command:
        #   - /bin/bash
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-ip-service
spec:
  type: ClusterIP 
  selector:
    component: kafka-1
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-2
  template:
    metadata:
      labels:
        component: kafka-2
    spec:
      containers:
      - name: kafka-2 
        image: pharosproduction/kafka_k8s:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 9092

        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-ip-service:2181
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: $(MY_POD_IP)
        tty: true
        livenessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 5
       
      imagePullSecrets:
        - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-ip-service
spec:
  type: ClusterIP 
  selector:
    component: kafka-2
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092



 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-3
  template:
    metadata:
      labels:
        component: kafka-3
    spec:
      containers:
      - name: kafka-3 
        image: pharosproduction/kafka_k8s:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 9092

        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-ip-service:2181
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: $(MY_POD_IP)
        tty: true
        livenessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 5
       
      imagePullSecrets:
        - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3-ip-service
spec:
  type: ClusterIP 
  selector:
    component: kafka-3
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092



  
      
